### ISSUE TITLE
Blockqoute ">" highlighting not available, all my blockqoutes are appearing as blank text

### ISSUE THREAD

**Issue by zuwf** [oqipoDev/garden-gnome-obsidian#2] opened 2024-01-04 05:03 UTC

**Comment by dhniceday** [comment] 2024-01-04 18:46
I can't reproduce it on my end. I have all CSS snippets deactivated and still highlight works in blockquotes.
Obsidian 1.5.3 running on Ubuntu 23.10

**Comment by oqipoDev** [comment] 2024-01-05 04:13
![image](https://github.com/oqipoDev/garden-gnome-obsidian/assets/100394455/b2982221-a897-4f2d-a003-51adb76dfeb7)

Can't reproduce in Obsidian 1.5.3 with the latest version.

Please provide this info:
* OS version
* Obsidian version
* Garden Gnome version
* CSS snippets used
* Screenshot

Otherwise I will have to close this issue.

**Comment by zuwf** [comment] 2024-01-05 10:32
I currently also tested with a fresh new vault in restricted mode and no CSS snippets used.

- OS                         :  Arch , Gnome
- Installer version : 1.5.3
- Current version  : 1.5.3

https://github.com/oqipoDev/garden-gnome-obsidian/assets/130776416/d316fc72-cdc8-4912-93e3-a1d7b19cca54

**Comment by zuwf** [comment] 2024-01-05 10:36
I currently also tested with a fresh new vault in restricted mode and no CSS snippets used.

- OS                         :  Arch , Gnome
- Installer version : 1.5.3
- Current version  : 1.5.3
- Theme Version   : 0.1.2

https://github.com/oqipoDev/garden-gnome-obsidian/assets/130776416/663b9d22-b6d6-4e0f-9f2b-56b2598d32b3

**Closed as completed** 2024-01-06 02:30 UTC

**Comment by oqipoDev** [comment] 2024-01-06 02:33
You were using Live Preview, and I didn't consider at first it as I use source mode, so this was a useful issue, feel free to report on more Live Preview issues in the future, as I'm blind to it :]

If everything's correct, the last update fixed it. I hope you enjoy it!

**Comment by zuwf** [comment] 2024-01-06 06:26
With pleasure, please add color chooser for headings and other text formats in style settings😇
